name: sync playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo -E make devcontainer-run-sync
        env:
          APPLE_BEARER_TOKEN: ${{ secrets.APPLE_BEARER_TOKEN }}
          APPLE_USER_TOKEN: ${{ secrets.APPLE_USER_TOKEN }}
