name: sync playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo -E make devcontainer-run-sync
